### ISSUE TITLE
Roadmap(chess)

### ISSUE THREAD

**Issue by Qinbeans** [Qinbeans/chess-htmx#1]
- [x] Move chess pieces
- [ ] Check legal moves
    - [x] Check if piece is in middle of path
    - [x] Check if piece can move to space
    - [ ] Refine checks
- [x] Use websockets
- [x] Check player color
- [x] Check player turn
- [x] Separate JS files
- [ ] Properly utilize HTMX
